### ISSUE TITLE
Integration test execution in Maven triggers JVM crash

### ISSUE THREAD

**Issue by VaughanJackson** [VaughanJackson/vocabulary-service#1]
* Of the 9 tests in the `VocabularyApplicationIntegrationTest` test class, only the `testAuthorisedOriginsAllowed` test manifests this issue.
* The test can be executed to successful completion using the same JDK directly in an IDE like Idea.
* However, if the same test is executed in Maven on the command line as follows, a JVM crash occurs (shown below):

`mvn -Dtest=VocabularyApplicationIntegrationTest#testAuthorisedOriginsAllowed test`

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:05 min
[INFO] Finished at: 2020-05-23T15:50:12+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project vocabulary-service: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/vaughanjackson/Dropbox/Projects/VocabularyDashboard/vocabulary-service/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/vaughanjackson/Dropbox/Projects/VocabularyDashboard/vocabulary-service && /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/bin/java -jar /Users/vaughanjackson/Dropbox/Projects/VocabularyDashboard/vocabulary-service/target/surefire/surefirebooter1298573807868273462.jar /Users/vaughanjackson/Dropbox/Projects/VocabularyDashboard/vocabulary-service/target/surefire 2020-05-23T15-49-07_646-jvmRun1 surefire7216943673886731768tmp surefire_09003822984448199873tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] com.learner.vocabularyservice.VocabularyApplicationIntegrationTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/vaughanjackson/Dropbox/Projects/VocabularyDashboard/vocabulary-service && /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/bin/java -jar /Users/vaughanjackson/Dropbox/Projects/VocabularyDashboard/vocabulary-service/target/surefire/surefirebooter1298573807868273462.jar /Users/vaughanjackson/Dropbox/Projects/VocabularyDashboard/vocabulary-service/target/surefire 2020-05-23T15-49-07_646-jvmRun1 surefire7216943673886731768tmp surefire_09003822984448199873tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] com.learner.vocabularyservice.VocabularyApplicationIntegrationTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
(base) vaughanjackson@Vaughans-MacBook-Pro vocabulary-service (master)
```
* No files seen in the `surefire-reports` directory referred to in the error messages.
* One characteristic of this test compared with the others is that it outputs a lot more information to the console as it executes.
* Apart from executing the test in an IDE, another way to avoid this crash is comment out the code in the test that prints out the result of the GET vocabulary request:

```
    @Test
    public void testAuthorisedOriginsAllowed() throws Exception {

        final String[] allowedOrigins = splitAllowedOrigins(properties.getCorsAllowedOrigins());
        LOGGER.debug("allowedOrigins = {}", allowedOrigins);

        for(final String origin: allowedOrigins) {
            LOGGER.debug("Testing allowed origin {} is allowed...", origin);
            expectGetCharactersRequestSuccess(mockMvc.perform(getCharactersRequest().header("Origin", origin))
                .andDo(print()));
            mockMvc.perform(getVocabularyRequest().header("Origin", origin))
                /*.andDo(print())*/      <=
                .andExpect(status().isOk());
        }
    }
```
* This problem is seen on a MacBook Pro with macOS Catalina Version 10.15.3 and is seen for two different JVMs:

```
(base) vaughanjackson@Vaughans-MacBook-Pro vocabulary-service (master) $ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-macosx) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-macosx) (build 25.212-b04, mixed mode)
```

and

```
(base) vaughanjackson@Vaughans-MacBook-Pro vocabulary-service (master) $ java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

* Maven version:

```
(base) vaughanjackson@Vaughans-MacBook-Pro vocabulary-service (master) $ mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T19:33:14+01:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 9, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Default locale: en_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
(base) vaughanjackson@Vaughans-MacBook-Pro vocabulary-service (master) $ 
```

**Comment by VaughanJackson** [comment]
Issue is **not** resolved by upgrading Maven:

```
(base) vaughanjackson@Vaughans-MacBook-Pro vocabulary-service (master) $ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_212, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
Default locale: en_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
(base) vaughanjackson@Vaughans-MacBook-Pro vocabulary-service (master) $
```

**Comment by VaughanJackson** [comment]
* Closing this issue with this workaround: https://github.com/VaughanJackson/vocabulary-service/commit/e7e10552883d95deafa6d1d9f9876d37a8c738c4.
